name: test

on:  
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    environment: test
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: |
            bun i
            bun run lint
            bun run test
        env:
          NODE_ENV: ${{ vars.NODE_ENV }}
          TZ: ${{ vars.TZ }}
          PGHOST: ${{ vars.PGHOST }}
          PGUSER: ${{ vars.PGUSER }}
          PGPASSWORD: ${{ vars.PGPASSWORD }}
          PGDATABASE: ${{ vars.PGDATABASE }}
          PORT: ${{ vars.PORT }}
          JWT_SECRET: ${{ vars.JWT_SECRET }}